apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: meshcentral
  namespace: meshcentral
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.truechartsoci.org
      chart: meshcentral
      version: 17.5.6
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  timeout: 20m
  values:
    global:
      stopAll: false
    credentials:
      cloudflare:
        type: s3
        url: "${CLOUDFLARE_BUCKET_URL}"
        bucket: "meshcentral"
        accessKey: "${CLOUDFLARE_BUCKET_ACCESS_KEY}"
        secretKey: "${CLOUDFLARE_BUCKET_SECRET_KEY}"
        encrKey: "${CLOUDFLARE_BUCKET_ENCR_KEY}"
    cnpg:
      main:
        password: ${POSTGRES_PW}
        cluster:
          singleNode: true
        mode: recovery
        backups:
          enabled: true
          revision: "1"
          credentials: cloudflare
        recovery:
          revision: ""
          credentials: cloudflare
    ingress:
      main:
        enabled: true
        ingressClassName: external
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
        hosts:
          - host: meshcentral.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
    meshcentral:
      domains:
        tcdefaultdomain:
          certUrl: meshcentral.${DOMAIN_0}
          title: MeshCentral
          title2: HoMSserver
      settings:
        cert: meshcentral.${DOMAIN_0}
    persistence:
      data:
        volsync:
          - name: app-data
            type: restic
            credentials: cloudflare
            dest:
              enabled: true
            src:
              enabled: false
      files:
        volsync:
          - name: files
            type: restic
            credentials: cloudflare
            dest:
              enabled: true
            src:
              enabled: false
      web:
        volsync:
          - name: web
            type: restic
            credentials: cloudflare
            dest:
              enabled: true
            src:
              enabled: false
      backups:
        volsync:
          - name: backup
            type: restic
            credentials: cloudflare
            dest:
              enabled: true
            src:
              enabled: false
