apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ddns-updater
  namespace: ddns-updater
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.truechartsoci.org
      chart: ddns-updater
      version: 12.4.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    global:
      stopAll: false
    credentials:
      cloudflare:
        type: s3
        url: "${CLOUDFLARE_BUCKET_URL}"
        bucket: "ddns-updater"
        accessKey: "${CLOUDFLARE_BUCKET_ACCESS_KEY}"
        secretKey: "${CLOUDFLARE_BUCKET_SECRET_KEY}"
        encrKey: "${CLOUDFLARE_BUCKET_ENCR_KEY}"
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
        hosts:
          - host: ddns-updater.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
    config:
      settings:
        - provider: cloudflare
          zone_identifier: "${DDNS_UPDATER_ZONE_IDENTIFIER}"
          domain: "${DOMAIN_0}"
          ttl: 600
          token: "${DDNS_UPDATER_TOKEN}"
          ip_version: ipv4
          ipv6_suffix: ""
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                CONFIG: "{{ .Values.config | toJson }}"
    persistence:
      data:
        volsync:
        - name: data
          type: restic
          credentials: cloudflare
          dest:
            enabled: false
          src:
            enabled: true
            trigger:
              schedule: 30 1 * * *
