apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ddns-updater
  namespace: ddns-updater
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.truechartsoci.org
      chart: ddns-updater
      version: 11.8.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    global:
      stopAll: false
    credentials:
      cloudflare:
        type: s3
        url: "${CLOUDFLARE_BUCKET_URL}"
        bucket: "actualserver"
        accessKey: "${CLOUDFLARE_BUCKET_ACCESS_KEY}"
        secretKey: "${CLOUDFLARE_BUCKET_SECRET_KEY}"
        encrKey: "${CLOUDFLARE_BUCKET_ENCR_KEY}"
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
        hosts:
          - host: ddns-updater.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
    persistence:
      data:
        volsync:
        - name: app-data
          type: restic
          credentials: cloudflare
          dest:
            enabled: true
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                CONFIG: ${DDNS_UPDATER_CONFIG}
