apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kubernetes-dashboard/ks.yaml
  - actualserver/ks.yaml
  - freshrss/ks.yaml
  - ddns-updater
  - grafana/ks.yaml
  - homepage
  - nextcloud/ks.yaml
