apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:up3/bmsQpEiPfapF0K//12++e8Hcs0fegWf/uy91IGdMt8kN5YTS10VCO49xyO7blKPVaXl+QFwsVkGlKU/BxdU=,iv:Ie6va1icZcDza85UTej32mm06SR9VJHc+/ZucLlqEF4=,tag:niohhkZbNC7H50o4yJBRFQ==,type:comment]
    #ENC[AES256_GCM,data:H5KbUnGAl1aj3iXjlgasjbYp1ounjwHNRmnu6BW96oL0HlVA5fFxCTHJGqk=,iv:pc/Pplrf2MxNqavey0jXu/KeckRNUDGQ4eu5Hng5SWU=,tag:NsvHLvf6Fkh6S8PM7E1nXQ==,type:comment]
    VIP: ENC[AES256_GCM,data:sAtT3/vlh1aF06ZkhQ==,iv:ZRQZiJgBw604+6GjAstmX1EfIm6toGhM8RQK3Q6AvIY=,tag:Ek1jchsP5CeNJQI84BC4pQ==,type:str]
    #ENC[AES256_GCM,data:qflHIW+jiCFJBl8/o4ZF+PAiFob43PjfRbnx,iv:YkyUZOb9/0B3STzq107i7hP5rrALu+xnCINjg9XEZ7g=,tag:BMxGb0kU1sQ+zgq16EaEmA==,type:comment]
    #ENC[AES256_GCM,data:VsPHosqKVRzq2+Ds5iwT5WYiqX3wCD00qf2epzScA4oaAyQ78o0N6ZciHLKRy6v8CuZa+fyRbdObuhV8ypHXwc7qFXRK2PD7TE954+W+Lfa74iBzZ01zhJM=,iv:tHCuQCHjKog0moQoqS+tvg4cgH4a1og6BDgkt0W6IWs=,tag:oP9FfjKtXANLSUVZUfiUWA==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:R2hJjrXwLI57cnyDrA==,iv:JrBeB1r5sZCDsEsLdHEvz7TVXw1sQ5VLJ+yGtj1UmBU=,tag:n1ky53OM8cg5JWvkXJjppg==,type:str]
    #ENC[AES256_GCM,data:5JxR4N3mjDnt6d6rvlmJJmW35VpKMDmzeMFVYV0EkqXvUg==,iv:j+EdrGBhZbPki/BUgA9W4jUqtYCOmacnXupGyVuPeh4=,tag:DruQc7wwoDEZ9I2PD9Mcyw==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:N6aeYn10y25zHNg=,iv:z5Ru33sKvFIfgdA0XF1LvEf/QeFJc0UY5sNke02moY0=,tag:5mwcobsEB4fQfgHE22zThQ==,type:str]
    #ENC[AES256_GCM,data:NLISaFmYTQKJy+vN6UJuNf4L4TQ6a2EX8IYYObvbQAvh+Xbal83lyzu7rwmBE9Y=,iv:b9Y7S+hPylOOcrgpk7/kiuCowgq6d8TstXqTmxYgE8Q=,tag:/VuF5yprddW7/8jgTlJVVQ==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:73bCHkgiWlWB+v0lThMinSZPevbjHkKRu+rP,iv:+pX2rOOG4VAGplu5bOaFBZC8o518d1nQ3P7BqBQQIfI=,tag:zBUZEo7OUlO05k+3nMKu0Q==,type:str]
    #ENC[AES256_GCM,data:TwjMOXIdyDvDezsGEYLg6tv7WRbrs+M2VjZgb5s1+yF/4F/7Z3JTQY0e08ElQJtHDabeZ3I7ITEPkhNP/gzBGZKSmupRQ3g/nMaa1F4SBTG/iQ==,iv:mhD4CAib+ZsgWPgay1Vzgk+JOVKtn6POX+FJwPEwW0o=,tag:ZVAro5bAq2z9lNH+tDVfzA==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:4p8/Q1LtQfjtP3KAKA==,iv:gnohZ2cY0UOkQ1AsMPKeo/Bw9+P8jdavW8jb7lJPEoo=,tag:nOZt3d2Bd9c1Wf+4KssBBA==,type:str]
    #ENC[AES256_GCM,data:KM0yEdNuLlMZI7UrnVcvUVk+iHvSCQ8H05SDRKlUumkE,iv:QwuXjF5/8hiyjnHvpWPurbEGLziNjMbyly6ph4Wh84Q=,tag:CWFxO25M5hSbEx+loKngkg==,type:comment]
    BLOCKY_IP: ENC[AES256_GCM,data:X6kqFL6UpihJ4xOEFQ==,iv:YX/E5uR+gHDnmjgGzIbMktpzuVWmBOb3+M8PduMDnWo=,tag:A3QKPYsQI1Qmi/maSubm7w==,type:str]
    #ENC[AES256_GCM,data:yFMaOhodfPrhQjTgl0721a4DOuxA+FJhnmC/FW7Kzu4wLkodV0lEbe2ZlElr6jJmfce+xSBedn1jHiez0Oly1EaD3kf+nW2k3btaoQXZ9Ko=,iv:roUl5sxaDRuBihtjvkQDJ9mWpKjf84aQe6mN4V7vecE=,tag:Po5I4LtYcqrQEgT22q5lGg==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:2Sr1BzDhXNOlGinXig==,iv:3D1J6vjYRQzq+uvO8qhROIJdiHzAUNUpuxmxBDFWCzI=,tag:/hj3Qc3QSnClWbXi46BrxA==,type:str]
    #ENC[AES256_GCM,data:OUtQyHLo6K1OiqfLRU3FBqc4F68RtpFt04dVYn/PWF87Vxx8nGoWnMhtMnmifKpj2ZOs1QBeSnePL0+7iXsjYrNz6Udsv/ffGoDgxRHYTG627Z7TWWtP,iv:7O/K5izz2cJ9EgtE9FM9YMNmmRh6yw2c4sR6QNQyt8w=,tag:Dv46aRNP0Emgbb/G8qhsyQ==,type:comment]
    #ENC[AES256_GCM,data:VuAqIsDK3jaqXgOnrgThjBWzwUQr6ykdkgfYCiHuMJTF4CBX43d5nDBXficuVO8pFO27WUFwrfiYa7QZxlAws0DPSxCiNiOhg+R6TtCYcIH2ZGXGh9+MfnEk5SlVd1/Livyr3PQGrceIitVOnXjqIXrF/J8zDAjDwJG1sA==,iv:/3LpPhH+11dYTEYN6ZIS7NEHHHcVLCOcrIb1kBzRwAc=,tag:MjvZ+Zsk9J7J8C/G8rBvLg==,type:comment]
    #ENC[AES256_GCM,data:ViLJCS6JJkD3CXTxnamPBhwZzWq+ZmQxSk24b6JfOoHTxAYrwONtShHi9Nq/+tVP0RAI3ESyiauExtTElmVcCTkh6gkD0X6MiwWao2YcCO4=,iv:7di7k18I94t509gKQtcds4E8OTqGWurdOJ2IdwMH61M=,tag:cyWS1SyWecGR3C1VhmW+lg==,type:comment]
    #ENC[AES256_GCM,data:dfu/2CIgRg76jNe+QVH9ZXGIW1PpJTux1BYr1JfO7XGBrdYMxWvf+iEfNCJT7PNVNhHvPGHG,iv:KGAaeemxIMhC7ObjyRF8v7jC2K4FP0B+C1nr4YeWeLg=,tag:0/OO1GpGh150jAH8qgqRPQ==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:SWA8ZTOEBHTLUmy/s5I=,iv:fo0EywGIvZtaWPAllSGLzIN31WQIefFGqdAHzdnOyN4=,tag:zqCgXs7LFi7ry0AdBojl5w==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:uLX+ecIP7XL8vEnQ+aduGgyGo2fDUgnp,iv:q7cow4s9OIefDM0OgjjM3b6/GdzhG80nFxnG0poaQ+k=,tag:mgh08ByP/pGnJ9k0tREJBA==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:hWRJtA6KCEoqRThq8BioUCHl4SZxUtbyLz0lIhY8P1swRJCDAX786w==,iv:LlI8UMrX0+F4yBmf7Q7ZlmWDLgjnmwtCVaOLtPhWB50=,tag:gOIKWqYOh0bQlfj+IPeJhQ==,type:str]
    #ENC[AES256_GCM,data:Afj+kPIQ9Vp/9O6GMxW8eYyZ0dNN157C9iTz8ehlNRemzl4fi4F5TR1RGiRotfhjtChOHiqh2s0=,iv:XCr5xDX3UYX4LEH6IC1Unp0kF33HCrKBO4a0GWUPLhI=,tag:wogEVZtWVWR/6sX6mN+26Q==,type:comment]
    #ENC[AES256_GCM,data:ws23xQXA58ahKO3P7CBzdnupHAcGMgmyuA==,iv:fs3qv95sjGyxuPGd4YfOJ64BsUbJ2eojm1g/y0YmAxg=,tag:6vZsy4Of/oQ4x22HjQZzjg==,type:comment]
    #ENC[AES256_GCM,data:FMQpskNyxWkkmpQmRj+sMw6zCtfeaHVEvhamTGmwfzGDIP/wbZF/xnrhTjbTFByAlBS9JhWmqtoAZCGCGs6C8CQSG0P2JDkYvYfhLV8=,iv:0ZJJbaQbndVXhk0ka9E9qMF652FExf3oG3n9I4qujY4=,tag:yFUWu3NVpxjCY9BU8zoOQw==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:8nPcm/r6pCUIMDjyWSfyxKZzpHQpMHSffcJmj2/cY7Ev8xmMYdITxyqlZRRWlA==,iv:8sSaXtuB9IW5Ixe78e/BfSmPI3GwBl/TnjLu+dHY4rM=,tag:DC3jijIJLaGzztDkxNzxmA==,type:str]
    #ENC[AES256_GCM,data:Ui1++0UzPStZLKvt9zCS95iV67ObxOWQsULKFYwxDGHucx7Ye3AM7gScTpgKiQwRem/5cUiTOQQUGDkAbqfzd/Pw4WA5v3g=,iv:pFCJdjXWtzQ3MkALSIQqD+sitSkx647vx65jwarbqDo=,tag:NLghHLiYo9VUTp6Z7CJtbg==,type:comment]
    #ENC[AES256_GCM,data:xALGzm34LNCd93MbZ6xQkTRxBkWPnMfLvao14C3fxkfUXGndgHkkZ+E/ZZiCUQsjzAEFtyV9,iv:rfV1XCUv4TpOFwfwg0hlW6O71z4SUHI4YjdYeJyH8hY=,tag:8jk8T6y04TC4vrZUfR8u8A==,type:comment]
    #ENC[AES256_GCM,data:q3Y6wbPJZ4OZlx37NTKJIfP27E+mfV07Ds0Unpe6vPpYmsA=,iv:bcjZGtpEYVWGLiAjoODmB5rcSqOyHXuCDV1gt1GPQZI=,tag:2b8R7w3kOlouKudeAAmD/A==,type:comment]
    #ENC[AES256_GCM,data:aeXnh1xhn/zStBhqTH6PRWjvcyCbSMwpfmseWaU+6eecx06D6KJ+,iv:Z4PwIHmXSJiUsDRhL6LHwzoP2qpmY66LL2JwqgXOqNM=,tag:XWWM3cdcKmW/vk2RoPIXPQ==,type:comment]
    #ENC[AES256_GCM,data:TKXL+PauT+BfNY+8L8M=,iv:KIGTs9zIxq3sBdd8vLWXVw58VDO3mPAXxXBFyLfHrTc=,tag:6XxKnG7jLdEi9YaxG7U7xQ==,type:comment]
    PODNET: ENC[AES256_GCM,data:p5WlorfDk+yFYmQIqA==,iv:RdarJGU64GYZgX5TjFE8Q0MWNiiB8RTeRqWY9q8jbIk=,tag:RRGUVcxij9JmzRrKxiIJTQ==,type:str]
    SVCNET: ENC[AES256_GCM,data:2nVYmOd+7CdcCMXA/w==,iv:K6quqPt6rfwNGzt8ASnd367jrKsTjjM/pQDn3NxvIC4=,tag:NbWnxZh4LRpbh746MsP7Fg==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:3xAfKg==,iv:nsV7cWBPGVMOKLb/W81retBF/ZpIYUl00nPul/wxlk0=,tag:E7vL9OImA/nUL2dFHNTeXQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u0d8mmt6zm570dyzke7f2z3rj068hmcltfkvve7qvx5jd78cpgeskcxmnv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzbElMMEVOOUVXbXBuSEk4
            QUVwVEo3RVdwckRUUHd0b3hLRlozeGZPN1EwCkk2YlBHZzZpejNGbytnSEVVS05R
            bGZLRWdHU0xVVmV0a0tkUVIxMm1PTHMKLS0tICtJb1JQMFMwZkZFR2xLZXdRYi8x
            VWFRSTNOWGpKSEt6N3BlWTBQY2pqQTgKXlnERCcoFLmKA3tkf9v0uSShAXKUf3TW
            tOyZdMSirYkAD9ps2wFvi0ZxvQb8+QX6XO6ej5fdFUdlaSIuRT0hCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-20T22:07:21Z"
    mac: ENC[AES256_GCM,data:VtjfJe8VybS36nouz5NAbG6Q/yFQxTAurVLnbP60LsEsUN048VLaXh8AXY/tG93wTn4ITDhN4XIlgcgF0cqQOpstYf9G1s1tQ+6KGhg4MMlCTYVs+WN1syGjl3kQu6usG6kSdUHeB3UiRGs9h4ebHK8101k062UNNjDX0aU0kJI=,iv:4gVi+ukvXyxQs8mBpsbX6ASAeVoATdFl5FPi7hs0u6k=,tag:hL6HUm5KFAKw5hxWIco0NA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
