apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:J7MVeLbG8VSzDeo6yZO+iidEavs8EJER9Yv8T9dK5yKmJI4ZIZQj7TfrK/VlvzzSnmcK3GE8p3m5N0WQvVwtGcMAOoCV75z5vmtbZamUw3FZrVF/EksgQVqX6ndDKvD+S7YVy/CZMIMPvHA5LWqAFw4nMi3aYyf65t1U3GerErswyVTFBN39CHT6h2qzu+EnSZdzt5FDQXHA6qo0RFIwmV0Gw2RXrf8wcFu9tBLDQM+ehOROOm1yI084sWev/u6TEBw0lUgTYjvFGmBiK6p+e/hIqFZlOvjLFOn6GBc56P785C0WmSHQDN+9wHeHtCLdPTNwvtcl5yS4O3MaO//6esPGEpUm3U2l6/IjNCsBFmXHz0gS+8RvLKidQatNjsEX,iv:irwASxoSvp0VvDbcbecw7GRiwIA7w4eLtuvt3bSdLAE=,tag:8njFRedbCpmsgCArGOqgvg==,type:str]
    identity.pub: ENC[AES256_GCM,data:exR2hjbWpXz5ZC2mCun87MAeuhETqFm72GraB37rpbIiZiSz+a1KuMi0tIH9OqPfx7Pu+q2gh9/7jrQaeOly0mFYpAZz1iEEHmkPOIMzGvJ7DvTO+MoQqwjXN4B2ZuqoxGAaNIoEfAJ+nX92LJ/pizRpGyXpw6e4IdKGmajmBbcIDrasFxkXmolhufS3cyVFbHtXiGGarMWqfvrjJSydIJ0al1uVPj1KkCBRVIPnTSTcmKqIbWtzuyLkzOImpcpKqzyG0E50LCLXAsGKuA==,iv:uYo//hEShhQZB+AxGpbKL3Pyez6MEQTKBGvUickw2xk=,tag:VbDqsKq5aq4MbLj628+VHQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:TFNBWDyuo6+8WHQcbj50G3Ufy1QUQ1yf7VqMNX0uucQmVWtuiSThfb9OEVi2/x/MoSHeZrBSBeBOkXVBiYx3I54PybLZaabq2FxvGu/RpNWRghm7EJkC0DsLCrJbT+pZVtR8efmD7Xe3Gwtk8OcRd3tHcdBBYK8Nmmi1N5mwvqGIAGFbWDmncZeL8nIA7N5E9gDnvlwrBb9flyRNuDjgMkkk7aakqEfgpzk2,iv:VF3NpbPAuPjtTEgUSYX631uwQrsFUqG9SbMUK9b4WZo=,tag:e+oXbsOOuadWQYjDbWOacg==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVNGdEd3lvVjI4NDlFdUU2
            b1Q2T3QvNVFDcjJnc2JwUERwd3lkdVBtVkZjCmg5cllzc2tVM0lnQmVlK256a241
            VFBIaXhib0JWQXRRNnkwMGNIeC9QYlEKLS0tIC9pQ3plWDhyK0FXV0p0cjlhb3Ry
            VDQ0dVovdUZVOFU0ZmJyajRmMHNJN1kK05q+ELbNfNGabXQjy7hHoZ9GiOXtcnJ4
            VsQxQmUbs9ennxg1pqiohxn0cjxxOMb1dkceHSoTNW/1ezHJvNYSOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u0d8mmt6zm570dyzke7f2z3rj068hmcltfkvve7qvx5jd78cpgeskcxmnv
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-09-14T10:32:12Z"
    mac: ENC[AES256_GCM,data:WVwpy0pLtv6JRKRSjRqYOPrjSpJA3XbzDIK4YnMsSIPm2dP/1se2qhhcGWvienXOfTvT8A1suZcTnVcnYOBA7NuC5pDvUd+/+Cx2FrJ3I3eqTKW2kZiyWkLmzx/hOqV7RrLCNHskUTT0ZXzuNmNQL2Y8oO7cwiZsqw8pdZWZ4+w=,iv:tNoZhk0qWdW/G0m32oasNb5X44SzISSoFCNFmctU0Wg=,tag:BK3F3Xljw7UDEF//l8KlOw==,type:str]
    shamir_threshold: 3
    version: 3.13.1
