# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 5m
  chart:
    spec:
      chart: immich
      version: 19.48.7
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    TZ: Europe/Berlin
    global:
      stopAll: false
    credentials:
      cloudflare:
        type: s3
        url: "${CLOUDFLARE_BUCKET_URL}"
        bucket: "immich"
        accessKey: "${CLOUDFLARE_BUCKET_ACCESS_KEY}"
        secretKey: "${CLOUDFLARE_BUCKET_SECRET_KEY}"
        encrKey: "${CLOUDFLARE_BUCKET_ENCR_KEY}"
    cnpg:
      main:
        password: ${POSTGRES_PW}
        cluster:
          singleNode: true
        #mode: recovery
        backups:
          enabled: true
          revision: "0"
          credentials: cloudflare
          scheduledBackups:
            - name: daily-backup
              schedule: "0 15 0 * * *"
              backupOwnerReference: self
              immediate: true
              suspend: false
        #recovery:
          #revision: "1"
          #credentials: cloudflare
    immich:
      log_level: debug
    ingress:
      main:
        enabled: true
        ingressClassName: external
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
          homepage:
            enabled: true
            group: Media
            name: Immich
            widget:
              enabled: false
        hosts:
          - host: immich.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
    persistence:
      profile:
        volsync:
          - name: profile
            type: restic
            credentials: cloudflare
            dest:
              enabled: false
            src:
              enabled: true
              trigger:
              schedule: 20 4 * * *
      thumbs:
        type: nfs
        server: ${TRUENAS_IP}
        path: /mnt/MAIN/immich/thumbnails
      backups:
        type: nfs
        server: ${TRUENAS_IP}
        path: /mnt/MAIN/immich/backups
      library:
        type: nfs
        server: ${TRUENAS_IP}
        path: /mnt/MAIN/immich/library
      uploads:
        type: nfs
        server: ${TRUENAS_IP}
        path: /mnt/MAIN/immich/upload
      video:
        type: nfs
        server: ${TRUENAS_IP}
        path: /mnt/MAIN/immich/video
      extlib1:
        enabled: true
        type: nfs
        server: ${TRUENAS_IP}
        mountPath: /usr/src/app/external/Lib1
        path: /mnt/MAIN/Pictures
        readonly: true
        targetSelector:
          # Main pod/container is server
          main:
            main: {}
          microservices:
            microservices: {}
